#!/usr/bin/env bash

ssh root@159.89.200.152 " \
	cd hcmus-conference && \
  cd backend && \
  git fetch origin && \
  git reset --hard origin/release && \
  npm install && \
  cp .env.production .env && \
  pm2 reload all
"