const plenaryPresentationData = [
  {
    startDate: new Date("December 18, 2020 8:30:00"),
    endDate: new Date("December 18, 2020 9:10:00"),
    name: "Cơ hội và thách thức trong nghiên cứu phát hiện và phát triển thuốc từ dược liệu Việt Nam",
    author: "PGS.TS. Nguyễn Thị Thanh Mai",
    biography: "PGS.TS. Nguyễn Thị Thanh Mai tốt nghiệp Đại học và Thạc sĩ ngành Hóa học tại Trường ĐH KHTN, ĐHQG-HCM, và Tiến sĩ Dược tại ĐH Y Dược Toyama, Nhật Bản. Hiện PGS.TS. Nguyễn Thị Thanh Mai nghiên cứu về lĩnh vực Hóa Dược, trong đó tập trung nghiên cứu hoạt tính sinh học và cấu trúc của các hoạt chất từ nguồn dược liệu Việt Nam. PGS.TS. Nguyễn Thị Thanh Mai đã thực hiện 11 đề tài NCKH các cấp, hiện đang chủ trì 3 đề tài NCKH khác; đã công bố 60 bài báo khoa học trên tạp chí quốc tế có uy tín; được trao tặng Giải thưởng Sáng tạo Thành phố Hồ Chí Minh năm 2019 và hiện là trưởng nhóm nghiên cứu Hóa Dược, được công nhận là Nhóm nghiên cứu mạnh của ĐHQG-HCM năm 2020.",
    summary: "Việt Nam là một quốc gia có nguồn dược liệu phong phú và đa dạng với trên 5.000 loài thực vật được sử dụng làm thuốc. Từ xa xưa, dân ta đã biết sử dụng các dược liệu tự nhiên để chữa bệnh rất hiệu quả. Song, vấn đề đặt ra là tại sao các loại dược liệu đó lại có tác dụng chữa trị và thành phần nào quyết định khả năng chữa trị của dược liệu đó? Trong những năm gần đây, các nghiên cứu về lĩnh vực Hóa Dược ở nước ta phát triển mạnh mẽ với mong muốn tạo ra các loại thuốc mới hoặc sản phẩm hỗ trợ sức khỏe nhằm phục vụ nhân dân, tận dụng nguồn dược liệu trong nước và ít lệ thuộc vào nguồn nguyên liệu nước ngoài. Trên tinh thần này, nhóm nghiên cứu của chúng tôi cũng đã thực hiện một số chương trình nghiên cứu về lĩnh vực Hóa Dược – Hóa hợp chất thiên nhiên, trong đó tập trung nghiên cứu các dược liệu cũng như các hợp chất có tác dụng điều trị các căn bệnh liên quan đến rối loạn nội tiết như bệnh đái tháo đường; rối loạn chuyển hóa như bệnh gout và sạm nám da; suy giảm trí nhớ như bệnh Alzheimer; kháng ung thư; kháng oxi hóa hoặc tác dụng giảm đau, kháng viêm khớp. Cho đến nay, chúng tôi đã sàng lọc hàng ngày cây thuốc, phân lập và xác định cấu trúc của khoảng 800 hợp chất, trong đó có khoảng 150 hợp chất mới và có trên 50 công bố quốc tế uy tín về lĩnh vực này. Ngoài ra, các nghiên cứu định hướng ứng dụng cũng được hình thành, bước đầu đã phát triển các sản phẩm hỗ trợ sức khỏe như kháng ung thư đường tiêu hóa và chống viêm loét dạ dày từ củ Ngải bún, kháng viêm khớp và giảm đau từ Cà gai leo,… Các kết quả đạt được cho thấy có nhiều cơ hội phát hiện và phát triển thuốc mới từ nguồn dươc liệu ở Việt Nam, từ đó góp phần phát triển ngành công nghiệp Dược bền vững.",
  },
  {
    startDate: new Date("December 18, 2020 9:10:00"),
    endDate: new Date("December 18, 2020 9:50:00"),
    name: "Phát triển đế SERS độ nhạy cao trên nền vật liệu cấu trúc bán dẫn 3D (ZnO nanorod và Si kim tự tháp) kết hợp hạt nano Ag/Au nhằm phát hiện vết thuốc trừ sâu",
    author: "PGS.TS. Lê Vũ Tuấn Hùng",
    biography: "PGS.TS. Lê Vũ Tuấn Hùng hoàn thành bậc học tiến sĩ  năm 2007 tại Trường Đại học Khoa học Tự nhiên, ĐHQG-HCM với chủ đề nghiên cứu về màng mỏng đa lớp quang học. PGS.TS. Lê Vũ Tuấn Hùng hiện đang là Trưởng khoa Vật Lý – Vật Lý Kỹ Thuật, trưởng bộ môn Vật Lý Ứng Dụng - Trường Đại học Khoa học Tự nhiên, ĐHQG-HCM. Trong các năm qua, PGS.TS. Lê Vũ Tuấn Hùng đã nghiệm thu 5 đề tài cấp ĐHQG-HCM và đã công bố 15 bài báo quốc tế ISI và nhiều bài báo trong các tạp chí trong nước. Hiện tại, PGS.TS. Lê Vũ Tuấn Hùng đang chủ trì Đề tài cấp nhà nước về chế tạo vật liệu khuếch đại tín hiệu quang phổ Raman.",
    summary: "Trong báo cáo này, nhóm nghiên cứu đã phát triển đế SERS (đế khuếch đại tín hiệu Raman bề mặt) dựa trên cấu trúc bán dẫn (ZnO nanorod và Si kim tự tháp) kết hợp với các hạt nano Au và Ag. Nhờ sự chuyển điện tích và liên kết hiệu quả giữa đế bán dẫn có cấu trúc 3D với các phân tử hữu cơ, và sự gia tăng tối đa hiện tượng cộng hưởng plasmon bề mặt từ các đám hạt nano (hot spot) đã gia tăng rất cao tín hiệu Raman. Hệ số khuếch đại tín hiệu EF có thể đạt > 106 – 107. Qua đó có thể phát hiện vết của thuốc trừ sâu, như Abamectin ở nồng độ rất nhỏ (<1ppm).",
  }
]

export default plenaryPresentationData